### ISSUE TITLE
暴露的接口可以通过验证器来鉴权，如增加@needtoken

### ISSUE THREAD

**Issue by gordon168** [china-wangyu/TRR#14]
暴露的接口可以通过验证器来鉴权，如增加@needtoken

**Comment by china-wangyu** [comment]
你好，@gordon168

你的想法💡，我了解了并思考🤔了一会，是个不错的点子。👍

但是这个想法💡，我思考结果是：

* *最好能自己解决，因为jwt在这个框架中，我放在了`Auth`类里面**

主要是以下几点：

- 业务场景和框架安全性的考虑，太过统一显得不够生动灵性。
- jwt的相关内容，我希望并期盼你们可以给出更好的方式
- 注解验证器来鉴权，我觉得用户可以根据自身的需要来完成

当然以上只是我个人看法，并不代表框架不会去实际和验证，也会争取使用者的意见。

反响大的话，TRR应该会出一个解决方案，提供给大家使用。

当前如果你个人想完成这个功能，建议参考 thinkphp中间件和 TRR 注解扩展使用。

附：

thinkphp中间件： https://www.kancloud.cn/manual/thinkphp5_1/564279
TRR注解扩展使用：https://china-wangyu.github.io/views/php/trr/v0.0.2/注解模型/

有什么疑问，欢迎提交你的意见。

**Comment by china-wangyu** [comment]
你好，@gordon168

你提出这个问题，在 #17 得到了解决。

使用文档参见：[点我](https://china-wangyu.github.io/views/php/trr/v0.0.2/jwt/#trr%E4%BD%BF%E7%94%A8jwt)

希望你拉取`最新`(master分支和v0.0.2分支)的代码，已满足你的需要。

谢谢🙏你的使用，祝你生活幸福😄。

**Comment by china-wangyu** [comment]
谢谢
